// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycgnnqzlcveajaefhoxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljZ25ucXpsY3ZlYWphZWZob3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTE5OTIsImV4cCI6MjA2NTcyNzk5Mn0.nQJs8H2RucdPtf0VAyJTEYS2KsLj3wv8_mb2Y4gKuGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);